name: 'Deep Security Smart Check'
description: 'Scan container images with Deep Security Smart Check.'
inputs:
  DSSC_IMAGE_NAME:
    description: Mandatory
    required: true
  DSSC_SMARTCHECK_HOST:
    description: ""
    required: true
  DSSC_SMARTCHECK_USER:
    description: ""
    required: true
  DSSC_SMARTCHECK_PASSWORD:
    description: ""
    required: true
  DSSC_IMAGE_PULL_AUTH:
    description: ""
    required: true
  DSSC_INSECURE_SKIP_TLS_VERIFY:
    description: Optional
    required: false
  DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY:
    description: ""
    required: false
  DSSC_PREREGISTRY_SCAN:
    description: ""
    required: false
  DSSC_PREREGISTRY_HOST:
    description: ""
    required: false
  DSSC_PREREGISTRY_USER:
    description: ""
    required: false
  DSSC_PREREGISTRY_PASSWORD:
    description: ""
    required: false
  DSSC_RESULTS_FILE:
    description: ""
    required: false
  DSSC_FINDINGS_THRESHOLD:
    description: ""
    required: false
branding:
  icon: 'check'
  color: 'red'
runs:
  using: "docker"
  image: "docker://deepsecurity/smartcheck-scan-action:latest"
  env:
    DSSC_IMAGE_NAME: ${{ inputs.DSSC_IMAGE_NAME }}
    DSSC_SMARTCHECK_HOST: ${{ inputs.DSSC_SMARTCHECK_HOST }}
    DSSC_SMARTCHECK_USER: ${{ inputs.DSSC_SMARTCHECK_USER }}
    DSSC_SMARTCHECK_PASSWORD: ${{ inputs.DSSC_SMARTCHECK_PASSWORD }}
    DSSC_IMAGE_PULL_AUTH: ${{ inputs.DSSC_IMAGE_PULL_AUTH }}
    DSSC_INSECURE_SKIP_TLS_VERIFY: ${{ inputs.DSSC_INSECURE_SKIP_TLS_VERIFY }}
    DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: ${{ inputs.DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY }}
    DSSC_PREREGISTRY_SCAN: ${{ inputs.DSSC_PREREGISTRY_SCAN }}
    DSSC_PREREGISTRY_HOST: ${{ inputs.DSSC_PREREGISTRY_HOST }}
    DSSC_PREREGISTRY_USER: ${{ inputs.DSSC_PREREGISTRY_USER }}
    DSSC_PREREGISTRY_PASSWORD: ${{ inputs.DSSC_PREREGISTRY_PASSWORD }}
    DSSC_RESULTS_FILE: ${{ inputs.DSSC_RESULTS_FILE }}
    DSSC_FINDINGS_THRESHOLD: ${{ inputs.DSSC_FINDINGS_THRESHOLD }}